flags: {}
packages:
- .
# - lilypond/
# - musicxml2/
# - music-articulation/
# - music-dynamics/
# - music-parts/
# - music-pitch/
# - music-score/
# - music-sibelius/
# - music-suite/
# - music-suite-app/
extra-deps:
- prettify-1.0
- average-0.6.1
- data-interval-1.2.0
# - hsini-0.5.0
- monadplus-1.4.2
- positive-0.4.1
- reverse-apply-2.0.1
- roman-numerals-0.5.1.5
- type-unary-0.2.19
- applicative-numbers-0.1.3
- extended-reals-0.2.1.0
# - ty-0.1.6
- ty-0.1.7
- vector-space-points-0.2.1.2
# - modular-arithmetic-1.2.1.1
- record-0.4.2
- basic-lens-0.0.0
# - combinat-0.2.8.1
resolver: lts-7.14
