version: 2
jobs:
  build:
    docker:
      - image: nixos/nix:2.3@sha256:af330838e838cedea2355e7ca267280fc9dd68615888f4e20972ec51beb101d8
        environment:
          LC_ALL: C.UTF-8
    steps:
      - checkout
      # TODO this is not fully reproducible because of Hackage revisions.
      # See
      #     https://twitter.com/refold/status/955782113797857281
      #     http://hackage.haskell.org/package/pantry-0.2.0.0/docs/Pantry.html#t:CabalFileInfo
      #     https://www.reddit.com/r/haskell/comments/7pb5tl/til_stackage_can_be_broken_retroactively_due_to/
      - run: nix-shell --pure --command "cabal update && cabal test"
