version: 2
jobs:
  build:
    docker:
      - image: nixos/nix:2.3
        environment:
          LC_ALL: C.UTF-8
    steps:
      - checkout
      - run: nix-shell --pure --command "cabal v2-update && cabal --reject-unconstrained-dependencies=all v2-test"
